/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spinning_top1;

/**
 *
 * @author Andres
 */
public class Spinning extends javax.swing.JFrame {

    /**
     * Creates new form Spinning
     */
    public Spinning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbljugador1 = new javax.swing.JLabel();
        lbljugador2 = new javax.swing.JLabel();
        lbljugador3 = new javax.swing.JLabel();
        lbljugador4 = new javax.swing.JLabel();
        txtplayer1 = new javax.swing.JTextField();
        txtplayer2 = new javax.swing.JTextField();
        txtplayer3 = new javax.swing.JTextField();
        txtplayer4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbljugadores = new javax.swing.JLabel();
        btnSpin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        cbxplayer = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jButton2.setText("jButton2");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Player ->");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 650));
        getContentPane().setLayout(null);

        jPanel3.setPreferredSize(new java.awt.Dimension(850, 850));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Play zone"));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("?");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 130, 87, 84);

        lbljugador1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbljugador1.setText("Player1");
        jPanel2.add(lbljugador1);
        lbljugador1.setBounds(170, 30, 60, 17);

        lbljugador2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbljugador2.setText("Player2");
        jPanel2.add(lbljugador2);
        lbljugador2.setBounds(310, 150, 60, 17);

        lbljugador3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbljugador3.setText("Player3");
        jPanel2.add(lbljugador3);
        lbljugador3.setBounds(170, 240, 60, 17);

        lbljugador4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbljugador4.setText("Player4");
        jPanel2.add(lbljugador4);
        lbljugador4.setBounds(30, 160, 60, 17);

        txtplayer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtplayer1);
        txtplayer1.setBounds(160, 70, 70, 40);

        txtplayer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtplayer2);
        txtplayer2.setBounds(310, 190, 60, 40);

        txtplayer3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtplayer3);
        txtplayer3.setBounds(170, 280, 70, 40);

        txtplayer4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtplayer4);
        txtplayer4.setBounds(30, 200, 60, 40);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Coins");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 50, 41, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Coins");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(320, 170, 40, 16);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Coins");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 260, 41, 16);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Coins");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 180, 48, 16);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(30, 60, 420, 340);

        lbljugadores.setText(".....");
        jPanel3.add(lbljugadores);
        lbljugadores.setBounds(180, 460, 220, 16);

        btnSpin.setBackground(new java.awt.Color(255, 0, 0));
        btnSpin.setText("Spin around ->");
        btnSpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpinActionPerformed(evt);
            }
        });
        jPanel3.add(btnSpin);
        btnSpin.setBounds(30, 410, 420, 40);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Config zone"));
        jPanel4.setLayout(null);

        btnPlay.setBackground(new java.awt.Color(0, 204, 102));
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel4.add(btnPlay);
        btnPlay.setBounds(30, 95, 70, 30);

        cbxplayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20", "30" }));
        jPanel4.add(cbxplayer);
        cbxplayer.setBounds(160, 30, 110, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Coins per player:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(20, 30, 120, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(500, 60, 300, 140);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acumulated", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(500, 210, 300, 90);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Winner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("?");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(500, 304, 300, 86);

        btnRestart.setBackground(new java.awt.Color(0, 153, 255));
        btnRestart.setText("Reiniciar juego");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });
        jPanel3.add(btnRestart);
        btnRestart.setBounds(510, 410, 290, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 860, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpinActionPerformed
        // TODO add your handling code here:
        
        
        
        
        lbljugadores.setText("" +lbljugador1);
        
        
        
        
        
        
    }//GEN-LAST:event_btnSpinActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        String Coins_per_player = "";
        Coins_per_player= Coins_per_player+cbxplayer.getSelectedItem().toString();
        txtplayer1.setText("" + Coins_per_player);
        txtplayer2.setText("" + Coins_per_player);
        txtplayer3.setText("" + Coins_per_player);
        txtplayer4.setText("" + Coins_per_player);
        
       
        
       
        
        
        
        
        
           
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        // TODO add your handling code here:
        
        
    txtplayer1.setText("0");
    txtplayer2.setText("0");
    txtplayer3.setText("0");
    txtplayer4.setText("0");
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spinning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spinning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnSpin;
    private javax.swing.JComboBox<String> cbxplayer;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbljugador1;
    private javax.swing.JLabel lbljugador2;
    private javax.swing.JLabel lbljugador3;
    private javax.swing.JLabel lbljugador4;
    private javax.swing.JLabel lbljugadores;
    private javax.swing.JTextField txtplayer1;
    private javax.swing.JTextField txtplayer2;
    private javax.swing.JTextField txtplayer3;
    private javax.swing.JTextField txtplayer4;
    // End of variables declaration//GEN-END:variables
}
